services:
  animarte:
    build:
      context: .
    image: nextjs-app
    container_name: animarte
    networks:
      - shared-network
    env_file:
      - .env.prod
    ports:
      - "2020:3000"
    expose:
      - "3000" # Asumiendo que tu app corre en el puerto 3500 dentro del contenedor

networks:
  shared-network:
    external: true
    name: shared-network-production
