services:
  animarte:
    build:
      context: .
    image: nextjs-app
    container_name: animarte
    networks:
      - shared-network
    env_file:
      - .env.prod
    ports:
      - '2020:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: always
    expose:
      - '3000'

networks:
  shared-network:
    external: true
    name: shared-network-production
